[package]
name = "http-server"
version = "0.1.0"
authors = ["danielcarney96 <dancarney@live.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
